docs: fix default config for Sentry
There is no option `active` anymore but the whole Sentry config
section is now optional. If `active` is set to false and an empty
DSN is specified as the current docs suggest, the following error /
backtrace (if enabled) is printed:

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: kids::cli::run
   2: std::sys::backtrace::__rust_begin_short_backtrace
   3: std::rt::lang_start::{{closure}}
   4: std::rt::lang_start_internal
   5: main
   6: <unknown>
   7: __libc_start_main
   8: _start
Error: no valid url provided

That's not really helpful in my opinion but I also do not know how to
properly fix this.
I would at least like to know for which field no valid URL was provided.